Repository openshift/osd-metrics-exporter, pull requests merged in 2020-10, with the labels that each got.

#4 Add controllers
  .codecov.yml
  .gitignore
  Makefile
  README.md
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/boilerplate-commit
  boilerplate/_lib/boilerplate.mk
  boilerplate/_lib/common.sh
  boilerplate/_lib/freeze-check
  boilerplate/generated-includes.mk
  boilerplate/openshift/golang-osd-operator/.codecov.yml
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/codecov.sh
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/golangci.yml
  boilerplate/openshift/golang-osd-operator/operator-sdk-generate.sh
  boilerplate/openshift/golang-osd-operator/project.mk
  boilerplate/openshift/golang-osd-operator/py-requirements.txt
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
  boilerplate/openshift/golang-osd-operator/validate-yaml.py
  boilerplate/update
  boilerplate/update.cfg
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  config/config.go
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/controller/add_controllers.go
  pkg/controller/clusterrole/clusterrole_controller.go
  pkg/controller/clusterrole/clusterrole_controller_test.go
  pkg/controller/controller.go
  pkg/controller/oauth/oauth_controller.go
  pkg/controller/oauth/oauth_controller_test.go
  pkg/metrics/aggregator.go
  pkg/metrics/metrics.go
  tools.go
  version/version.go
Labels: do-not-merge/hold, lgtm

#5 Added OWNERS file
  OWNERS
Labels: lgtm

#7 Boilerplate: Update to f435f4ab6213d69d6ffbe493435e8b062cf54684
  .ci-operator.yaml
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/boilerplate.mk
  boilerplate/openshift/golang-osd-operator/.ci-operator.yaml
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
Labels: approved, lgtm

#8 Reordered scheme initialization
  cmd/manager/main.go
Labels: approved, lgtm

#9 Register metrics from aggregator
  cmd/manager/main.go
Labels: approved, lgtm

#10 Added template for app-interface with operator stuff
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#11 Added scripts to build images and operator catalog
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/generate-operator-bundle.py
Labels: approved, lgtm

#13 Fixed the name of the saas repository
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#14 Ensure the directory with the bundle exists before generating bundles
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#15 Added cluster service version template
  config/templates/osd-metrics-exporter-csv-template.yaml
Labels: approved, lgtm

#16 Change the bundle generation script to not include CSVs
  hack/generate-operator-bundle.py
Labels: approved, lgtm

#17 Replace the yq image used
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#18 Fix name of OLM Catalog
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#19 Fixed the permissions for the operator
  deploy/cluster_role.yaml
Labels: approved, lgtm

#20 Fixed the version of operator-custom-metrics
  config/config.go
  go.mod
  go.sum
Labels: approved, lgtm

#21 Added update servicemonitor permission for operator
  deploy/cluster_role.yaml
Labels: approved, lgtm

#22 Update Boilerplate
  .ci-operator.yaml
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/_lib/freeze-check
  boilerplate/openshift/golang-osd-operator/.ci-operator.yaml
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/prow-config
  boilerplate/openshift/golang-osd-operator/standard.mk
  boilerplate/openshift/golang-osd-operator/update
  boilerplate/update
  build/Dockerfile
Labels: approved, lgtm

#25 Boilerplate: Update to f1bcadb4366d3f9fa0f0f14a445a3bac939daa8d
  .ci-operator.yaml
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/_lib/release.sh
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/codecov-secret-mapping
  boilerplate/openshift/golang-osd-operator/ensure.sh
  boilerplate/openshift/golang-osd-operator/prow-config
  boilerplate/openshift/golang-osd-operator/standard.mk
  build/Dockerfile
Labels: approved, lgtm

#26 Boilerplate: Update to 79550f8ca58f1990e817fc738962cdd37285b3ab
  .ci-operator.yaml
  boilerplate/_data/last-boilerplate-commit
  boilerplate/_lib/common.sh
  boilerplate/openshift/golang-osd-operator/.ci-operator.yaml
  boilerplate/openshift/golang-osd-operator/README.md
  boilerplate/openshift/golang-osd-operator/prow-config
  boilerplate/openshift/golang-osd-operator/standard.mk
Labels: approved, lgtm

#23 Change cluster-admin metric to be read from user group
  .gitignore
  cmd/manager/main.go
  deploy/cluster_role.yaml
  pkg/controller/add_controllers.go
  pkg/controller/clusterrole/clusterrole_controller.go
  pkg/controller/clusterrole/clusterrole_controller_test.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm

#28 Add .operator-sdk/* and *.orig to .gitignore
  .gitignore
Labels: approved, lgtm
